datasets:
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Hypersim/data_split_marigold_v2/test.json
    sampling_strategy: first:10
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/hypersim.py
    prob: 1.0
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/KenBurns/indoor_test.json
    sampling_strategy: first:2
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 100.0
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/kenburns.py
    prob: 1.0
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/DIML/test.json
    sampling_strategy: first:2
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1000.0
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/diml.py
    prob: 1.0
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/DynamicStereo/test.json
    sampling_strategy: first:2
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/dynamicstereo.py
    prob: 1.0
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Davinci/train_mf.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1000.0
    min_depth: 0.001
    max_depth: 200.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base.py

    type: hAlgorithm.datasets.lidar_depth_dataset.LidarDepthDataset
    name: davinci
    mf_to_sf: true
    mf_scene: "20240829_152118"
    mf_frame_id: 4
    mf_view_ids: [1, 2, 3]
    
  