datasets:
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Hypersim/data_split_marigold_v2/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/hypersim.py
    prob: 1.0 # syn
    name: hypersim

  - data_path: /mnt/netdata/Team/AI/datasets/TMD/KenBurns/indoor_train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 100.0
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/kenburns.py
    prob: 1.0 # syn
    name: kenburns
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/DynamicStereo/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 10.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/dynamicstereo.py
    prob: 1.0 # syn
    name: dynamicstereo
    
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/BlendedMVS/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/blendedmvs.py
    prob: 0.5 # mvs
    name: blendedmvs

  - data_path: /mnt/netdata/Team/AI/datasets/TMD/DIML/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1000.0
    min_depth: 0.001
    max_depth: 5.9
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/diml.py
    prob: 0.5 # mvs
    name: diml
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/ScanNet/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1000.0
    min_depth: 0.001
    max_depth: 10.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/scannet.py
    prob: 0.5 # mvs
    name: scannet

  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Taskonomy/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 512.0
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/taskonomy.py
    prob: 0.1 # lidar
    name: taskonomy
    
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/DIODE/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 60.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/diode.py
    prob: 0.1 # lidar
    name: diode
    
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/AgiBotWorld/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1000.0
    min_depth: 0.001
    max_depth: 2.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/agibot.py
    prob: 0.1 # depth camera
    name: agibot
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Matterport3D/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: true
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 30.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/matterport3d.py
    prob: 0.1 # depth camera
    name: matterport3d
  
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/STD/train.json
    sampling_strategy: all
    sparse_depth_ratio: 0.05
    only_pointmap: false
    with_pointmap: true
    depth_scale: 1.0
    min_depth: 0.001
    max_depth: 1.5
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/std.py
    prob: 0.1 # depth camera
    name: std