data = dict(
    train="hAlgorithm/configs/dataset/diffuser/sparse/base_train.yaml",
    val="hAlgorithm/configs/dataset/diffuser/sparse/small_test.yaml",
    vis="hAlgorithm/configs/dataset/diffuser/sparse/vis.yaml",
)

model = dict(
    type="hAlgorithm.modules.pipelines.depth_sd2_fm_pipeline.DepthSD2FlowMatchPipeline",
    pretrained_model_name_or_path="/mnt/netdata/Team/AI/weights/huggingface/stabilityai/stable-diffusion-2/",
    vae=None,
    unet=None,
    scheduler=dict(
        type="FlowMatchEulerDiscreteScheduler",
        num_train_timesteps=1000,
        shift=3.0,
        use_dynamic_shifting=False,
        base_shift=0.5,
        max_shift=1.15,
        base_image_seq_len=256,
        max_image_seq_len=4096,
    ),
    weighting_scheme="none",  # ["sigma_sqrt", "logit_normal", "mode", "cosmap", "none"]
    logit_mean=0.0,
    logit_std=1.0,
    mode_scale=1.29,
    depth_gt_type="depth_raw",  # match_input_res = True
    depth_gt_mask_type="depth_raw_mask",
    match_input_res=True,
    # depth_gt_type="depth", # match_input_res = True
    # depth_gt_mask_type="depth_mask",
    depth_type="depth_norm",
    depth_mask_type="depth_mask",
    sparse_depth_type=None,
    multi_res_noise=dict(
        strength=0.9,
        annealed=True,
        downscale_strategy="original",
    ),
    denoising_steps=1,
    min_depth=1e-3,
    max_depth=200.0,
)

trainer = dict(
    type="hAlgorithm.modules.trainers.diffusion_trainer.DiffusionTrainer",
    max_epoch=13,
    max_iter=None,
    num_workers=8,
    batch_size=32,
    gradient_accumulation_steps=1,
    lr=3.0e-05,
    lr_scheduler=dict(
        type="hAlgorithm.modules.lr_schedulers.Iter_exponential.IterExponential",
        total_iter=25000,
        final_ratio=0.01,
        warmup_steps=100,
    ),
    # max_grad_norm=1,
    eval_metrics=dict(
        type="hAlgorithm.modules.metrics.depthmap_eval_metrics.DepthEvalMetrics",
        target_name="depth_raw",
        valid_mask_name="depth_raw_mask",
        # target_name="depth",
        # valid_mask_name="depth_mask",
        gt_min_depth=1e-3,
        gt_max_depth=200.0,
        metrics=[
            "abs_relative_difference",
            "squared_relative_difference",
            "rmse_linear",
            "rmse_log",
            "log10",
            "delta1_acc",
            "delta2_acc",
            "delta3_acc",
            "i_rmse",
            "silog_rmse",
        ],
    ),
    main_eval_metric="rmse_linear",
    main_eval_metric_goal="minimize",
    in_evaluation=False,
    in_visualize=True,
    backup_period=0,
    val_period=2000,
    save_period=2000,
    vis_period=2000,
    accelerator_dynamic_batch=True,
    accelerator_dynamic_batch_key="image",
)
