"""Baseline-v3 decoupled scene-flow with pair cross-attention aggregator.

Changes vs `baseline_decoupled_sf_mlp.py`:
  - pair feature aggregation uses `PairCrossAttnAggregator` (learned cross-attn readout)
  - pair decoder uses *separated* heads so `warp3d` and `warp3d_delta*` are produced by
    independent parameter sets (no shared MLP trunk).

The displacement head still outputs `warp3d_delta_direction` (unit) +
`warp3d_delta_magnitude` (softplus); the pipeline composes `warp3d_delta = dir * mag`.
"""

patch_size = 14
max_size = 504

max_iter = 50000

view_num = 4
novel_view_nums = 0

select_dataset = "pointodyssey,hasim"
select_val_dataset = select_vis_dataset = "hasim_benchmark_running"

static_dataset_names = None
dynamic_dataset_names = [
    "pointodyssey",
    "kubric4d",
    "dynamicreplica",
    "cotracker3kubric",
    "hasim",
    "hasim_benchmark_running",
    "hasim_character_medium",
]

data = dict(
    train="hAlgorithm/configs/motion_head/datasets_config/train/with_hasim_0423.yaml",
    val="hAlgorithm/configs/motion_head/datasets_config/val/with_hasim_val_0423.yaml",
    vis="hAlgorithm/configs/motion_head/datasets_config/val/with_hasim_val_0423.yaml",
    basic=dict(
        sem_name="",
        with_pointmap_raw=True,
        interpolate_version=None,
        interpolate_k=0,
        normalize_cameras=True,
        with_global_scale=True,
        sparse_pattern=None,
        sparse_pattern_v2=None,
        sparse_pattern_v3=None,
        test_transforms=[
            dict(
                type="hAlgorithm.datasets.transforms.transforms.ResizeKeepRatio",
                max_size=max_size,
                patch_size=patch_size,
                is_lidar=False,
                low_resolution=True,
            ),
            dict(type="hAlgorithm.datasets.transforms.transforms.ToTensor"),
            dict(
                type="hAlgorithm.datasets.transforms.transforms.Normalize",
                mean=[127.5, 127.5, 127.5],
                std=[127.5, 127.5, 127.5],
            ),
        ],
    ),
    train_basic=dict(
        with_inf_mask=False,
        with_rgb_edge_mask=True,
        with_depth_edge_mask=True,
        clip_maxlen=None,
        clip_sampler=dict(
            type="hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler",
            view_num=view_num,
            seed=None,
            shuffle=False,
        ),
        novel_view_nums=novel_view_nums,
        sparse_pattern=None,
        sparse_pattern_v2=None,
        sparse_pattern_v3=None,
        train_transforms=[
            dict(
                type="hAlgorithm.datasets.transforms.transforms.ResizeKeepRatio",
                max_size=max_size,
                patch_size=patch_size,
                is_lidar=False,
                low_resolution=True,
                backup=True,
            ),
            dict(
                type="hAlgorithm.datasets.transforms.metric3d_transforms.PhotoMetricDistortion",
                to_gray_prob=0.1,
                distortion_prob=0.3,
            ),
            dict(
                type="hAlgorithm.datasets.transforms.metric3d_transforms.RandomBlur",
                prob=0.05,
            ),
            dict(
                type="hAlgorithm.datasets.transforms.metric3d_transforms.RGBCompresion",
                prob=0.1,
                compression=[0, 50],
            ),
            dict(type="hAlgorithm.datasets.transforms.transforms.ToTensor"),
            dict(
                type="hAlgorithm.datasets.transforms.transforms.Normalize",
                mean=[127.5, 127.5, 127.5],
                std=[127.5, 127.5, 127.5],
            ),
        ],
    ),
    val_basic=dict(
        clip_sampler=dict(
            type="hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory",
            view_num=4,
            seed=0,
        ),
    ),
    vis_basic=dict(
        clip_sampler=dict(
            type="hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory",
            view_num=4,
            seed=0,
        ),
    ),
)

model = dict(
    type="hAlgorithm.modules.pipelines2.mvfr_query_v4.WFMQueryPipeline",
    static_dataset_names=static_dataset_names,
    dynamic_dataset_names=dynamic_dataset_names,
    training_sub_pixel_scale=1,
    testing_sub_pixel_scale=1,
    scale_align=False,
    pair_mode=6,
    model=dict(
        type="hAlgorithm.modules.models2.sdk.query.MVQuery4",
        chunk_size=10000,
        decoder_fp32=False,
        fuse_encoder=dict(
            type="hAlgorithm.modules.models2.mv_encoder.da3_mv_encoder.DinoV2",
            normalize=True,
            patch_size=patch_size,
            name="vitg",
            out_layers=[19, 27, 33, 39],
            alt_start=13,
            qknorm_start=13,
            rope_start=13,
            cat_token=True,
        ),
        query_banck=dict(
            type="hAlgorithm.modules.models2.query_bank.single_view.QueryBank5",
            full_ratio=0.2,
            train_sampler=dict(
                type="hAlgorithm.modules.models2.query_bank.sampler.RandomSampler",
                num_samples=100000,
            ),
            timing=False,
            with_edge_mask=True,
            offset=0,
            noise=0.5,
            noise_ratio=0.0,
        ),
        query_feats_aggregator=dict(
            type="hAlgorithm.modules.models2.query_aggregator.infinidepth.Aggregator24",
            patch_size=patch_size,
            intermediate_layer_idx=[0, 1, 2, 3],
            in_chans=[3072, 3072, 3072, 3072],
            embed_dims=[256, 256, 256, 256],
            upsample_scales=[4, 2, 1, 1],
            mode="bilinear",
            interp_refinenet_cfg=dict(
                type="hAlgorithm.modules.models2.encoder.prompt_encoder.Resnet",
                layer_num=1,
                use_bn=False,
            ),
        ),
        query_decoder=dict(
            type="hAlgorithm.modules.models2.head.mlp_head.Head",
            in_chan=256,
            hidden_dim=64,
            names=dict(depth=1, confidence=1, global_points=3, global_confidence=1),
            acts=dict(depth="exp", confidence="", global_points="inv_log", global_confidence=""),
        ),
        camera_head=dict(
            type="hAlgorithm.modules.models2.head.camera_head.CameraHead",
            dim_in=3072,
            trunk_depth=4,
            pose_encoding_type="absT_quaR_FoV",
            num_heads=16,
            mlp_ratio=4,
            init_values=0.01,
            trans_act="linear",
            quat_act="linear",
            fl_act="relu",
        ),
        query_pair_feats_aggregator=dict(
            type="hAlgorithm.modules.models2.query_aggregator.pair_cross_attn_aggregator.PairCrossAttnAggregator",
            patch_size=patch_size,
            intermediate_layer_idx=[0, 1, 2, 3],
            in_chans=[3072, 3072, 3072, 3072],
            embed_dims=[256, 256, 256, 256],
            upsample_scales=[4, 2, 1, 1],
            mode="bilinear",
            interp_refinenet_cfg=dict(
                type="hAlgorithm.modules.models2.encoder.prompt_encoder.Resnet",
                layer_num=1,
                use_bn=False,
            ),
            # Cross-attention params (output layout keeps 3*256 width)
            cross_attn_dim=256,
            cross_attn_heads=8,
            cross_attn_layers=4,
            cross_ff_ratio=4,
            cross_dropout=0.0,
            # Keep Roma matching embed optionality consistent with PairQueryAggregator
            match_layer_idx=-1,
            match_dim=256,
            match_temp=0.1,
            match_scale=1.0,
            enable_amp=True,
            with_match_embed=True,
        ),
        # Separated heads: absolute warp3d vs displacement warp3d_delta*.
        query_pair_decoder=dict(
            type="hAlgorithm.modules.models2.head.separated_warp3d_and_delta_head.SeparatedWarp3dAndDeltaHead",
            warp3d_head=dict(
                type="hAlgorithm.modules.models2.head.mlp_head.Head",
                in_chan=256 * 3,
                hidden_dim=64,
                names=dict(
                    warp3d=3,
                    warp3d_confidence=3,
                ),
                acts=dict(
                    warp3d="inv_log",
                    warp3d_confidence="",
                ),
            ),
            delta_head=dict(
                type="hAlgorithm.modules.models2.head.mlp_head.Head",
                in_chan=256 * 3,
                hidden_dim=64,
                names=dict(
                    warp3d_delta_direction=3,
                    warp3d_delta_magnitude=1,
                    warp2d=2,
                    warp2d_confidence=4,
                ),
                acts=dict(
                    warp3d_delta_direction="norm",
                    warp3d_delta_magnitude="softplus",
                    warp2d="",
                    warp2d_confidence="",
                ),
            ),
        ),
    ),
    intrinsics_name="intrinsics",
    extrinsics_name="extrinsics_reff",
    scale_name="sparse_pointmap_max_range",
    prompt_depth_name=None,
    prompt_depth_mask_name=None,
    target_local_depth_name="pointmap_raw",
    target_global_points_name="pointmap_raw_reff",
    target_depth_mask_name="depth_raw_mask",
    target_normal_name=None,
    target_motion_mask_name=None,
    target_invalid_mask_name=None,
    align_name="depth_raw",
    edge_mask_name="edge_mask",
    motion_extrinsics_name="extrinsics",
    local_depth_l1_loss=dict(
        type="hAlgorithm.modules.losses2.points_l1_loss.ZWeightedLoss",
        loss_weight=1.0,
        with_conf=True,
        valid_range=0.99,
    ),
    local_depth_grad_loss=None,
    local_depth_normal_loss=dict(
        type="hAlgorithm.modules.losses2.normal_cos_loss.NormalCosineLoss",
        target_is_normals=False,
        valid_range=0.95,
        loss_weight=dict(default=0.0),
    ),
    local2global_loss=None,
    local_normal_loss=None,
    global_points_l1_loss=dict(
        type="hAlgorithm.modules.losses2.points_l1_loss.GlobalPointZWeightedLoss",
        loss_weight=1.0,
        with_conf=True,
        valid_range=0.99,
    ),
    global_points_grad_loss=None,
    global_points_normal_loss=None,
    camera_loss=dict(
        type="hAlgorithm.modules.losses2.camera_loss.Pi3CameraLoss",
        loss_type="l1",
        gamma=0.6,
        pose_encoding_type="absT_quaR_FoV",
        weight_T=1.0,
        weight_R=10.0,
        weight_fl=0.5,
        frame_num=-100,
        loss_weight=1.0,
    ),
    rc_rgb_l1_loss=None,
    rc_ssim_loss=None,
    rc_lpips_loss=None,
    rc_depth_loss=None,
    rc_normal_loss=None,
    motion_sample_mean=True,
    motion_dynamic_threshold=0.01,
    query_motion2d_loss=dict(
        type="hAlgorithm.modules.losses2.query_match_loss.QueryMatchLoss",
        alpha=0.5,
        scale_c=1e-4,
        conf_weight=0.01,
        precision_weight=0.01,
        precision_thresh=1.0,
        loss_weight=dict(default=5.0, pointodyssey=0.0),
    ),
    query_motion3d_loss=dict(
        type="hAlgorithm.modules.losses2.points_l1_loss.GlobalPointZWeightedLoss",
        loss_weight=10.0,
        with_conf=True,
    ),
    query_motion3d_delta_loss=dict(
        type="hAlgorithm.modules.losses2.sparse_motion_loss.SparseDisplacementQueryMotion3dDeltaLoss",
        loss_weight=50.0,
        dynamic_threshold=0.02,
        balance_weight=0.85,
        detach_log_scale=False,
        batch_reduction="per_example_mean",
        pool_static_dynamic=False,
    ),
    warp3d_delta_direction_loss=dict(
        type="hAlgorithm.modules.losses2.sparse_motion_loss.SparseDirectionLoss",
        loss_weight=1.0,
        mag_threshold=0.02,
        static_mag_weight=1.0,
    ),
    query_motion_mask_loss=dict(
        type="hAlgorithm.modules.losses2.query_track3d_loss.QueryMotionMaskLoss",
        loss_weight=1.0,
        valid_range=None,
    ),
    task_weight=dict(
        lcl=1.0,
        glb=1.0,
        l2g=1.0,
        cm=10.0,
        tk=0.03,
        rc=1.0,
        match=1.0,
        motion=1.0,
    ),
    pose_encoding_type="absT_quaR_FoV",
    save_output_cfg=dict(
        save_everything=False,
        save_gaussians=False,
        save_render_results=False,
        save_glb_results=False,
        save_glb_sf_results=False,
        save_glb2local_results=False,
        save_local2glb_results=False,
        save_cameras=False,
        save_local_results=False,
        save_track_results=False,
        save_filtered_results=False,
        output_normalize_cameras=True,
        output_match_input_res=True,
        output_conf_ratio=0.2,
        save_match=False,
        save_motion=True,
        # Passed to ``vis_sparse_motion_3d_rerun`` (see ``mvfr_query_v4``): extra Rerun panels for warp3d / warp3d_delta.
        rerun_vis_cfg=dict(
            enable_prediction=True,
        ),
    ),
)

trainer = dict(
    type="hAlgorithm.trainers.moge_trainer.MogeIterTrainer",
    skip_error_step=True,
    select_dataset=select_dataset,
    select_val_dataset=select_val_dataset,
    select_vis_dataset=select_vis_dataset,
    sampler="MixedMaxIterBatchSampler",
    max_epoch=None,
    max_iter=max_iter,
    num_workers=8,
    batch_size=1,
    gradient_accumulation_steps=1,
    set_random_size=False,
    max_grad_norm=1,
    lr=None,
    lr_scheduler=dict(
        type="hAlgorithm.modules.lr_schedulers.cosine_lr_updater.CosineLrUpdater",
        base_lr=1e-4,
        max_iters=max_iter,
        warmup_iters=1000,
        warmup="linear",
        warmup_ratio=1e-6,
        min_lr=1e-8,
    ),
    optimizer={
        "type": "AdamW",
        "model.fuse_encoder": dict(lr=1e-5, betas=(0.9, 0.999), weight_decay=1e-3, eps=1e-10),
        "model": dict(lr=1e-4, betas=(0.9, 0.999), weight_decay=1e-3, eps=1e-10),
        "strict_match": True,
        "debug": False,
    },
    eval_metrics=dict(
        type="hAlgorithm.modules.metrics.multi_eval_metrics.MultiEvalMetrics",
        metrics=[
            dict(
                type="hAlgorithm.modules.metrics.combined_eval_metrics.CombinedEvalMetrics",
                task="Camera",
                eval_groups=[dict(type="hAlgorithm.modules.metrics.pose_eval_metrics.PoseEvalMetricsV2")],
            ),
            dict(
                type="hAlgorithm.modules.metrics.combined_eval_metrics.CombinedEvalMetrics",
                task="Dyn_pts",
                eval_groups=[
                    dict(
                        type="hAlgorithm.modules.metrics.sparse_motion_eval_metrics_v2.SparseMotionEvalMetrics",
                        dynamic_threshold=0.01,
                        apd_thresholds_3d=[],
                        inlier_threshold_3d=None,
                        apd_thresholds_2d=[],
                        inlier_threshold_2d=None,
                        dynamic_only=True,
                        require_visible=True,
                        with_dy_ratio=False,
                        metric_prefix="dy_",
                    ),
                    dict(
                        type="hAlgorithm.modules.metrics.sparse_motion_eval_metrics_v2.SparseMotionEvalMetrics",
                        dynamic_threshold=0.01,
                        apd_thresholds_3d=[],
                        inlier_threshold_3d=None,
                        apd_thresholds_2d=[],
                        inlier_threshold_2d=None,
                        dynamic_only=False,
                        require_visible=True,
                        with_dy_ratio=True,
                    ),
                ],
            ),
            dict(
                type="hAlgorithm.modules.metrics.combined_eval_metrics.CombinedEvalMetrics",
                task="Scene_flow",
                eval_groups=[
                    dict(
                        type="hAlgorithm.modules.metrics.sparse_motion_eval_metrics_v2.SparseMotionEvalMetrics",
                        dynamic_threshold=0.01,
                        apd_thresholds_3d=[],
                        inlier_threshold_3d=None,
                        apd_thresholds_2d=None,
                        dynamic_only=True,
                        require_visible=True,
                        with_motion_mask=False,
                        with_warp3d_delta=True,
                        with_dy_ratio=False,
                        metric_prefix="dy_",
                    ),
                    dict(
                        type="hAlgorithm.modules.metrics.sparse_motion_eval_metrics_v2.SparseMotionEvalMetrics",
                        dynamic_threshold=0.01,
                        apd_thresholds_3d=[],
                        inlier_threshold_3d=None,
                        apd_thresholds_2d=None,
                        dynamic_only=False,
                        require_visible=True,
                        with_motion_mask=False,
                        with_warp3d_delta=True,
                        with_dy_ratio=False,
                    ),
                ],
            ),
        ],
    ),
    main_eval_metric="Camera|auc_1",
    main_eval_metric_goal="maximize",
    in_evaluation=False,
    in_visualize=False,
    backup_period=100000,
    val_period=1000,
    save_period=1000,
    vis_period=10000,
    accelerator_dynamic_batch=True,
    accelerator_dynamic_batch_key="image",
    # Load same baseline checkpoint; motion head keys differ (expected missing/unexpected).
    load_from="/mnt/nasTeam/AI/Autoresearch/Algorithm/Pretrain/MVS/mv_query_260413_baseline/mv_rgb_query_lgc_260413_bs1_4f_50k_20260414-151231/checkpoint/latest/ckpt.pth",
)
