datasets:
  # kosmo
  - data_path: [
      /mnt/nasTeam/Kosmo/processed_data/kosmo/20260117_8_诺坎普/诺坎普_newdrc_暗光增强/raw_data/data_hgaussian_v1.0.1_normal_mvfr_v251105_sfm_colmap_v1.4.0_mask_mos_v1.1.2_depth_mvfr_v251105@20260105210001.json,
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/home/stang/workspace/TMA2
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kosmo_fisheye_6
    sampling_strategy: [10, 50, 70]
    mf_scene_sampling_strategy: all
    mf_view_ids: [6]
    type: hAlgorithm.datasets_fisheye.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    # drop_last: false
    # with_depth_raw: false
    rbg_name: rgb
    depth_name: none
    mask_name: none
    sem_name: none
    normal_name: none
    lidar_name: none
    eval_mask_name: none
    disparity_name: none
    pre_crop_edge: [500, 0]
    camera_type: "FISHEYE_EQUIDISTANT"
    fisheye_edge_value: 300
    fisheye_edge_pixel: 30
  
  - data_path: [
      /mnt/nasTeam/Kosmo/processed_data/kosmo/20260117_8_诺坎普/诺坎普_newdrc_暗光增强/raw_data/data_hgaussian_v1.0.1_normal_mvfr_v251105_sfm_colmap_v1.4.0_mask_mos_v1.1.2_depth_mvfr_v251105@20260105210001.json,
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/home/stang/workspace/TMA2
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kosmo_fisheye_7
    sampling_strategy: [10, 50, 70]
    mf_scene_sampling_strategy: all
    mf_view_ids: [7]
    type: hAlgorithm.datasets_fisheye.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    # drop_last: false
    # with_depth_raw: false
    rbg_name: rgb
    depth_name: none
    mask_name: none
    sem_name: none
    normal_name: none
    lidar_name: none
    eval_mask_name: none
    disparity_name: none
    pre_crop_edge: [500, 0]
    camera_type: "FISHEYE_EQUIDISTANT"
    fisheye_edge_value: 300
    fisheye_edge_pixel: 30
