datasets:
  - data_path: results/mv_8f_250714/rc_vggt_250707_obj_infini_mvpdcg_bs1_8f_backup_20250714-174912/outputs/iter_000001/ios/data_info_with_depth.json
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    name: ios

    sampling_strategy: all
    mf_scene_sampling_strategy: all

    meta_json: /mnt/netdata/Team/AI/datasets/TMD/Benchmark/Gaussian/metadata/metadata.json
    meta_json_split: val

    # mf_scene: 一个手握小风扇
    # mf_frame_ids: [0, 25, 51, 76, 102, 128, 153, 179]
    # mf_scene: 一个瓷茶杯
    # mf_frame_ids: [0, 25, 51, 77, 103, 129, 155, 181]
    # mf_scene: 一大瓶立白洗洁精
    # mf_frame_ids: [0, 25, 51, 76, 102, 127, 153, 178]
    # mf_scene: 一大盒趣多多巧克力味饼干
    # mf_frame_ids: [0, 26, 53, 80, 107, 134, 161, 188]
    # mf_scene: 一罐可乐
    # mf_frame_ids: [0, 25, 50, 75, 100, 125, 150, 175]

    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    only_pointmap: true
    with_pointmap: true
    # min_depth: 0.001
    # max_depth: 64.0
    type: hAlgorithm.datasets_mv.iphone_dataset.IphoneDatasetMV
    mf_to_mv: true
    clip_maxlen: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 8

    depth_name: lidar_depth
    info_frame_ids: true

    intrinsics_name: pred_intrinsic
    extrinsics_name: pred_extrinsic
    depth_name: pred_depth
    lidar_name: pred_depth

    # confidence: 0
    # confidence_name: None

    

