# Training config: 4 opensource datasets + HaSim
# PointOdyssey + Kubric4D + DynamicReplica + CoTracker3Kubric + HaSim

datasets:
  # PointOdyssey
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/PointOdyssey/train_mf_with_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: pointodyssey
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.pointodyssey_track_dataset.PointOdysseyTrackDataset
    mf_to_mv: true
    clip_maxlen: 24
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  # Kubric-4D
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Kubric-4D/train_mf_with_tracking_2048.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kubric4d
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.kubric4d_track_dataset.Kubric4DTrackDataset
    mf_to_mv: true
    clip_maxlen: 24
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  # DynamicReplica (val split)
  - data_path: [
      /mnt/netdata/Team/AI/datasets/TMD/DynamicStereo/val_mf_stereo_with_trajs.json,
      /mnt/netdata/Team/AI/datasets/TMD/DynamicStereo/test_mf_stereo_with_trajs.json
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: dynamicreplica
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    # prob: 1.0
    prob: 0.1
    type: hAlgorithm.datasets_4d.dynamicreplica_track_dataset.DynamicReplicaTrackDataset
    mf_to_mv: true
    clip_maxlen: 24
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  # # DynamicReplica (test split)
  # - data_path: /mnt/netdata/Team/AI/datasets/TMD/DynamicStereo/test_mf_stereo_with_trajs.json
  #   only_pointmap: true
  #   with_pointmap: true
  #   min_depth: 0.001
  #   max_depth: 20.0
  #   point_normalize_mode: "distance"
  #   data_root: /mnt/netdata/Team/AI/datasets/TMD/
  #   pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
  #   name: dynamicreplica
  #   sampling_strategy: all
  #   mf_scene_sampling_strategy: all
  #   prob: 1.0
  #   type: hAlgorithm.datasets_4d.dynamicreplica_track_dataset.DynamicReplicaTrackDataset
  #   mf_to_mv: true
  #   clip_maxlen: 24
  #   clip_step: null
  #   clip_sampler:
  #     type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
  #     view_num: 4
  #     seed: null

  # CoTracker3 Kubric
  - data_path: /mnt/nasTeam2/AI/datasets/TMD/CoTracker3_Kubric/cotracker3_kubric.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: cotracker3kubric
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.pointodyssey_track_dataset.PointOdysseyTrackDataset
    mf_to_mv: true
    clip_maxlen: 24
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  # HaSim (train split with val excluded)
  # 物体
  - data_path: /mnt/nasTeam2/AI/datasets/TMD/Hasim_pinhole_4D/hasim_4d_mf_train_split_with_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hasim
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.hasim_track_dataset.HaSimTrackDataset
    skip_static_threshold: 0.02
    static_traj_ratio: 1.2
    mf_to_mv: true
    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null
    
  - data_path: /mnt/nasTeam2/AI/datasets/TMD/Hasim_benchmark/Running/mf_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hasim_benchmark_running
    sampling_strategy: all
    mf_scene_sampling_strategy: "end:-5"
    prob: 0.1
    type: hAlgorithm.datasets_4d.hasim_track_dataset.HaSimTrackDataset
    skip_static_threshold: 0.02
    static_traj_ratio: 1.0
    mf_to_mv: true
    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null
  
  # 人物
  - data_path: /mnt/nasTeam2/AI/datasets/TMD/Hasim_pinhole_4D_character_medium/hasim_4d_mf_train_split_with_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hasim_character_medium
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.hasim_track_dataset.HaSimTrackDataset
    skip_static_threshold: 0.02
    static_traj_ratio: 1.2
    mf_to_mv: true
    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null
  
  - data_path: /mnt/nasTeam2/AI/datasets/TMD/Hasim_pinhole_4D_character_follow/hasim_4d_mf_train_split_with_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hasim_character_follow
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.hasim_track_dataset.HaSimTrackDataset
    skip_static_threshold: 0.02
    static_traj_ratio: 1.2
    mf_to_mv: true
    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  - data_path: /mnt/nasTeam2/AI/datasets/TMD/Hasim_pinhole_4D_character/hasim_4d_mf_train_split_with_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hasim_character
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.hasim_track_dataset.HaSimTrackDataset
    skip_static_threshold: 0.02
    static_traj_ratio: 1.2
    mf_to_mv: true
    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  - data_path: /mnt/nasTeam2/AI/datasets/TMD/Hasim_pinhole_4D_character_easy/hasim_4d_mf_train_split_with_tracking.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 20.0
    point_normalize_mode: "distance"
    data_root: /mnt/nasTeam2/AI/datasets/TMD
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hasim_character_easy
    sampling_strategy: all
    mf_scene_sampling_strategy: all
    prob: 1.0
    type: hAlgorithm.datasets_4d.hasim_track_dataset.HaSimTrackDataset
    skip_static_threshold: 0.02
    static_traj_ratio: 1.2
    mf_to_mv: true
    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

  # 室内，场景，仿真
  # name hypersim
  # mf_data_scene 768
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 3629
  # mf_data_scene_frames max 100, min 6, mean 97, median 100   
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Hypersim_new/total_mf.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hypersim
    sampling_strategy: all
    mf_scene_sampling_strategy: first:-10
    prob: 0.1

    type: hAlgorithm.datasets_mv.base_dataset.BaseDatasetMV
    mf_to_mv: true
    clip_maxlen: 24
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null
  
  # 室内，场景，仿真
  - data_path: /mnt/nasTeam2/AI/datasets/TMD/DL3DV-10K/resolution_1080P_anno/train_mf_sparse.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: dl3dv
    sampling_strategy: all
    mf_scene_sampling_strategy: first:-10
    prob: 0.1

    type: hAlgorithm.datasets_mv.sparse_dataset.SparseDatasetMV
    mf_to_mv: true
    clip_maxlen: null
    clip_step: 5
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
      view_num: 4
      seed: null

    sparse_gt_name: sparse_gt

    mf_scene_delete: [
      3K/063d0a7a6f0cbfd789396403a4b4b6df6e69e7aa21571b79a28d6905d3041e87,
      3K/4fbfd34fd694f51029f9affb4edbe08aabb2c89060a5575a74e928c5fe8b60a3,
      5K/c4d941f6ef10c931149b9b3029fa832a7b7121d31223c7fa4212f9190242b19a,
      2K/3671f05fc0771dcd7751d2a397ae01a05aa509ca48f3ca1d9295053512608a92,
      2K/b3afe638605b6db2e70bdc818ab572e97579e754bf7e145a9905c56b44c21f5e,
      2K/75339b67b51893d96efd78eb9c75d7f8addcfc87c18785a51593bf561b194ef7,
      7K/95111a7236ae9cbb72ad27b35b7a2eafdef389cb169bb6576a523e28e6abb048,
      10K/a7cc00c501c536cd0355f8175816e1436873e90213f49a36ba8ffeb1670aeb6,
      9K/8275c23418681ad9a9be7c1de312c169a63b7837f8fa59b1fd8a2df6b38a170b,
      2K/77528f38efe78019fc9eb83b1ddbab8f29ee8e43483437acb92a958796f5bdd4,
      5K/231cf352c577f234cc6300a79f205bc45b7f7320862d87769f699820204d417e,
      9K/8870e2ea8af3d2d6cb774ad81f00c6335c1214dc143c6257d67b2a7b0b05c958,
      8K/093809e60e3b0e891a80773d5f519583583aec70979487ccdc448e10cfe5f818,
      4K/ccb638e7641bea603f5e29dab3dc7886583c16b2836ba4c3512f391cd23ae6a6,
      1K/1a0dc4cda12b60b6eb02464b8164944a6fd28bf92341e46b5ca1271526e4c0ad,
      3K/721fecd89f6e29527dafb19cbb05a925ce91df44c2ae4778116a08d20c6ab8b6,
      7K/56fbffb029487e4cac6dc83851f847a3293a3723f185d0fb95dca4c1b7c3f725,
      7K/7f4f307d483203fca9e1c1b484708a5f3e7fc22de56287b7850aabbb87cb3351,
      5K/d1329c1e76a70a938ee7bcb565634297ef59c6141debaa12c21e699aa77609ae,
      5K/05be8d80bb93df842f2caff2e295a7f9f9ef2cbbfdd03b85f5d80a009fc631af,
      3K/533f672b771aa2efd4da4ffa4dac6b5d89406a8455e253c67b365df53690e312,
      3K/2528bdf56322f47636550955f4d1c4d8f1562655b99018da61d1a67687f91c39
    ]
    # reproject_error_thresh: 1