datasets:
  # name hypersim
  # mf_data_scene 1
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 5
  # mf_data_scene_frames max 100, min 100, mean 100, median 100
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Hypersim_new/total_mf.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hypersim
    sampling_strategy: [0]
    mf_scene_sampling_strategy: end:1
    prob: 1.0

    type: hAlgorithm.datasets_mv.base_dataset.BaseDatasetMV
    mf_to_mv: true
    clip_maxlen: 20
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    normal_name: normal_svd
    with_inf_mask: true
    inf_mask_depth_nan: true
  
  # name scannet
  # mf_data_scene 1
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 50
  # mf_data_scene_frames max 5920, min 5920, mean 5920, median 5920
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/ScanNet/train_mf_split_10.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 8.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: scannet
    sampling_strategy: [0]
    mf_scene_sampling_strategy: end:1
    prob: 1.0

    type: hAlgorithm.datasets_mv.base_dataset.BaseDatasetMV
    mf_to_mv: true
    clip_maxlen: 120
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
  
  # name scpp
  # mf_data_scene 1
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 45
  # mf_data_scene_frames max 1071, min 1071, mean 1071, median 1071
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/ScanNetPP_Processed/iphone_val_mf_arkit_render.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: scpp
    sampling_strategy: [0]
    mf_scene_sampling_strategy: first:1
    prob: 1.0

    type: hAlgorithm.datasets_mv.base_dataset.BaseDatasetMV
    mf_to_mv: true
    # clip_maxlen: 10
    clip_step: 6
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    depth_name: render_depth
    rbg_name: rgb
  
  # name hablendeder_objs
  # mf_data_scene 1
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 23
  # mf_data_scene_frames max 180, min 180, mean 180, median 180
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/HaSim/HaBlender/Front3D/front3d_objs_surround_hemisphere_objaverse_20250616_part1_10.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 64.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: hablendeder_objs
    sampling_strategy: [0]
    mf_scene_sampling_strategy: end:1 # NOTE: 第一个场景有问题

    type: hAlgorithm.datasets_mv.base_dataset.BaseDatasetMV
    mf_to_mv: true
    # clip_maxlen: null
    clip_step: 2
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    hdf5: true
    rbg_name: rgb
    depth_name: depth
    # normal_name: "normals"
    normal_name: none
    mask_name: none
  
  # 室外，场景，仿真
  # name mvssynth
  # mf_data_scene 120
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 1560
  # mf_data_scene_frames max 100, min 100, mean 100, median 100
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/MVS-synth/train_mf.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 200.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: mvssynth
    sampling_strategy: [0, 25, 50]
    mf_scene_sampling_strategy: end:1

    type: hAlgorithm.datasets_mv.base_dataset.BaseDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    normal_name: normal_svd
    with_inf_mask: true
    inf_mask_depth_nan: true
  
  # name iphone
  # mf_data_scene 1
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 13
  # mf_data_scene_frames max 205, min 205, mean 205, median 205
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/naspersonal/zm/mvs3.0/test_mf_v2_v3_compare_smallobj.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 64.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: iphone
    sampling_strategy: [0]
    mf_scene_sampling_strategy: [0]
    # mf_scene: "一个手握小风扇"
    prob: 1.0

    type: hAlgorithm.datasets_mv.iphone_dataset.IphoneDatasetMV
    mf_to_mv: true
    clip_maxlen: 16
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1

    depth_name: lidar_depth
    # delete_camera: true
  
    # confidence: 1
  
  # name patagonia
  # mf_data_scene 1
  # mf_to_mv True sf_to_mf False
  # mf_data_scene_mf 13
  # mf_data_scene_frames max 55, min 55, mean 55, median 55
  # mf_data_scene_views max 1, min 1, mean 1, median 1
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/Zed2FT/data/20250429_maxwell/patagonia/20250429_182841_pose.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 64.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: patagonia
    sampling_strategy: [0, 1]
    mf_scene_sampling_strategy: all
    mf_view_ids: [0]

    type: hAlgorithm.datasets_mv.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 4
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    lidar_name: lidar_depth

  # kosmo
  - data_path: [
      /mnt/nasTeam/Kosmo/json/kosmo/20251119/6560_11F健身房晚上20左目.json,
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/home/stang/workspace/TMA2
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kosmo_0
    sampling_strategy: [100, 200, 300]
    mf_scene_sampling_strategy: all
    mf_view_ids: [0]

    type: hAlgorithm.datasets_mv.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    # drop_last: false
    # with_depth_raw: false
    
    rbg_name: rgb
    depth_name: none
    mask_name: none
    sem_name: none
    normal_name: none
    lidar_name: lidar_depth
    eval_mask_name: none
    disparity_name: none

  # kosmo
  - data_path: [
      /mnt/nasTeam/Kosmo/json/kosmo/20251119/6560_11F健身房晚上20左目.json,
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/home/stang/workspace/TMA2
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kosmo_1
    sampling_strategy: [100, 200, 300]
    mf_scene_sampling_strategy: all
    mf_view_ids: [1]

    type: hAlgorithm.datasets_mv.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    # drop_last: false
    # with_depth_raw: false
    
    rbg_name: rgb
    depth_name: none
    mask_name: none
    sem_name: none
    normal_name: none
    lidar_name: lidar_depth
    eval_mask_name: none
    disparity_name: none
  
  # kosmo
  - data_path: [
      /mnt/nasTeam/Kosmo/json/kosmo/20251119/6560_11F健身房晚上20左目.json,
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/home/stang/workspace/TMA2
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kosmo_2
    sampling_strategy: [100, 200, 300]
    mf_scene_sampling_strategy: all
    mf_view_ids: [2]

    type: hAlgorithm.datasets_mv.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    # drop_last: false
    # with_depth_raw: false
    
    rbg_name: rgb
    depth_name: none
    mask_name: none
    sem_name: none
    normal_name: none
    lidar_name: lidar_depth
    eval_mask_name: none
    disparity_name: none
  
  # kosmo
  - data_path: [
      /mnt/nasTeam/Kosmo/json/kosmo/20251119/6560_11F健身房晚上20左目.json,
    ]
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 1000.0
    point_normalize_mode: "distance"
    data_root: /mnt/home/stang/workspace/TMA2
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: kosmo_3
    sampling_strategy: [100, 200, 300]
    mf_scene_sampling_strategy: all
    mf_view_ids: [3]

    type: hAlgorithm.datasets_mv.lidar_depth_dataset.LidarDepthDatasetMV
    mf_to_mv: true
    clip_maxlen: 1
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.debug_trajectory.DebugTrajectory
      view_num: 1
    
    # drop_last: false
    # with_depth_raw: false
    
    rbg_name: rgb
    depth_name: none
    mask_name: none
    sem_name: none
    normal_name: none
    lidar_name: lidar_depth
    eval_mask_name: none
    disparity_name: none
  
    

    
