datasets:
  - data_path: /mnt/netdata/Team/AI/datasets/TMD/TartanAir/train_mf.json
    only_pointmap: true
    with_pointmap: true
    min_depth: 0.001
    max_depth: 100.0
    point_normalize_mode: "distance"
    data_root: /mnt/netdata/Team/AI/datasets/TMD/
    pipeline: hAlgorithm/configs/dataset/pipeline_14x/base4d.py
    name: tartanair_step30
    mf_scene_sampling_strategy: all
    prob: 1.0

    type: hAlgorithm.datasets_mv.tartanair_dataset.TartanAirDatasetMV
    sem_name: sem
    with_inf_mask: false
    inf_mask_sem_names: ['sky']
    
    mf_to_mv: true
    # clip_step: 5
    # clip_sampler:
    #   type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomClipSampler
    #   view_num: 2
    #   seed: null
    #   shuffle: false
    
    mf_to_sf: false


    clip_maxlen: null
    clip_step: null
    clip_sampler:
      type: hAlgorithm.datasets_mv.clip_sampler.random_sampler.RandomIntervalClipSampler
      interval: 30
      view_num: 2
      seed: null
      shuffle: true

      debug: true
